VERSION --wait-block 0.6

all:
    WAIT
        BUILD +othersubdirimage
    END
    FROM alpine
    RUN --push echo push

othersubdirimage:
    FROM ../subdir+subdirimage
    RUN echo othersubdirimage > /data
    SAVE IMAGE --push othersubidrimage:test
