VERSION --wait-block 0.6

all:
    WAIT
        BUILD +subdirimage
    END
    FROM alpine  # this led to reproducing it
    RUN --push echo push

subdirimage:
    FROM alpine
    RUN echo subdirimage > /data
    SAVE IMAGE --push subidrimage:test
